### PR TITLE
Update wasm package version

### LINKED ISSUE #169: Build failure
```
ocamlbuild -I src -I lib -I parser -I kremlib -use-menhir -use-ocamlfind -classic-display -menhir "menhir --infer --explain" Kremlin.native
ocamlfind ocamlc -c -g -annot -bin-annot -strict-sequence -w @1-2-3@8..12@14..21@23..29-30@31..38-39-40-41@43@57 -package ppx_deriving.std -package ppx_deriving_yojson -package zarith -package pprint -package unix -package menhirLib -package sedlex -package process -package fix -package wasm -package visitors.ppx -package visitors.runtime -I src -I parser -I kremlib -I lib -o src/CFlatToWasm.cmo src/CFlatToWasm.ml
+ ocamlfind ocamlc -c -g -annot -bin-annot -strict-sequence -w @1-2-3@8..12@14..21@23..29-30@31..38-39-40-41@43@57 -package ppx_deriving.std -package ppx_deriving_yojson -package zarith -package pprint -package
unix -package menhirLib -package sedlex -package process -package fix -package wasm -package visitors.ppx -package visitors.runtime -I src -I parser -I kremlib -I lib -o src/CFlatToWasm.cmo src/CFlatToWasm.ml
File "src/CFlatToWasm.ml", line 196, characters 18-32:
196 |   [ dummy_phrase (W.Ast.TeeLocal (mk_var (env.n_args + 2)));
                        ^^^^^^^^^^^^^^
Error: Unbound constructor W.Ast.TeeLocal
Command exited with code 2.
Makefile:22: recipe for target 'minimal' failed
make: *** [minimal] Error 10
```

I am using wasm 1.1, maybe that's the problem?

### PR DESCRIPTION
**Pull request by phase**
Closes #169

I also updated the maximum OCaml version to `< 4.10.0` since I could build with `4.09.1`.

### CODE REVIEW

**Comment by msprotz** [comment]
Thanks! I've never seen the syntax you used for `PKG` in the `_merlin` file. Do you have a reference for that?

**Comment by phase** [comment]
My mistake, I assumed I had to specify the version there too but it looks like Merlin doesn't care.

**Comment by msprotz** [comment]
Thanks! Much appreciated.
